# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\ImageService:
        arguments:
            $imageRepository: '@App\Repository\ImageRepository'
            $fileUploadService: '@App\Service\FileUploadService'

    App\Service\FileUploadService:
        arguments:
            $filesystem: '@flysystem.adapter.mys3_storage'

    flysystem.adapter.mys3_storage:
        class: League\Flysystem\AwsS3V3\AwsS3V3Adapter
        arguments:
            - '@aws_s3_v3.client'
            - '%env(AWS_BUCKET)%'
            - '' # optional prefix

    aws_s3_v3.client:
        class: Aws\S3\S3Client
        arguments:
            -
                region: '%env(AWS_REGION)%'
                version: 'latest'
                credentials:
                    key: '%env(AWS_KEY)%'
                    secret: '%env(AWS_SECRET)%'

# AWS S3 Client for Flysystem
    aws_s3_v3:
        class: Aws\S3\S3Client
        arguments:
            -
                version: 'latest'
                region: '%env(AWS_REGION)%'
                credentials:
                    key: '%env(AWS_ACCESS_KEY_ID)%'
                    secret: '%env(AWS_SECRET_ACCESS_KEY)%'
    App\Service\S3Service:
        arguments:
            $s3Client: '@aws_s3_v3'
            $bucket: '%env(AWS_BUCKET)%'
            