flysystem:
    storages:
        s3.storage:
            adapter: 'aws'
            options:
                client: 'aws_s3_v3'
                bucket: '%env(S3_BUCKET)%'
                prefix: 'images'
