flysystem:
    storages:
        s3.storage:
            adapter: 'aws'
            options:
                client: 'Aws\\S3\\S3Client'
                bucket: '%env(S3_BUCKET)%'
                prefix: 'images'
