twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        aws_bucket: '%env(S3_BUCKET)%'
        aws_region: '%env(AWS_REGION)%'
        
when@test:
    twig:
        strict_variables: true
