twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        images_directory: 'uploads/images/'
        aws_bucket: '%env(AWS_BUCKET)%'
        aws_region: '%env(AWS_REGION)%'
        
when@test:
    twig:
        strict_variables: true
