twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        images_directory: 'uploads/images/'
        
when@test:
    twig:
        strict_variables: true
